sudo: false
language: go
go:
  - 1.7
  - 1.8
before_install:
  - go get -t -v ./parser/...
  - go get -t -v ./swagger/...
  - go get -t -v ./test/...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=swagger.coverprofile ./swagger
  - go test -coverprofile=parser.coverprofile ./parser
  - gover
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
